import { StyleSheet, Dimensions, Platform } from "react-native";

export const makeStyles = (C) => StyleSheet.create({
  container:{flex:1,backgroundColor:C.bg},
  header:{backgroundColor:C.bg,borderBottomWidth:1,borderBottomColor:C.border,paddingTop:48,paddingBottom:12,paddingHorizontal:16},
  headerRow:{flexDirection:"row", alignItems:"center", justifyContent:"space-between"},
  headerTitle:{fontSize:22,fontWeight:"900",color:C.primary, textAlign:"center", flex:1},
  headerSub:{fontSize:12,color:C.subtext,marginTop:4, textAlign:"center"},
  headerAvatarBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: C.soft, borderWidth: 1, borderColor: C.border, alignItems: 'center', justifyContent: 'center' },
  headerAvatarImg: { width: '100%', height: '100%', borderRadius: 18 },
  searchRow:{flexDirection:"row",alignItems:"center",padding:12},
  searchInput:{flex:1,backgroundColor:C.soft,padding:12,borderRadius:12,borderWidth:1,borderColor:C.border,color:C.text},
  clearBtn:{padding:12,marginLeft:8,borderRadius:10,backgroundColor:C.soft,borderWidth:1,borderColor:C.border},
  segmentsWrap:{paddingHorizontal:12,paddingBottom:8,backgroundColor:C.bg,borderBottomWidth:1,borderBottomColor:C.border},
  segments:{alignItems:"center",paddingVertical:8},
  segmentPill:{borderWidth:1,borderColor:C.border,paddingHorizontal:14,paddingVertical:10,borderRadius:999,marginRight:8,backgroundColor:C.bg},
  segmentPillActive:{backgroundColor:C.primary,borderColor:C.primary},
  segmentText:{color:C.text,fontWeight:"700"},
  segmentTextActive:{color:"#FFFFFF",fontWeight:"800"},
  card:{backgroundColor:C.bg,borderRadius:14,padding:16,marginHorizontal:12,marginTop:12,borderWidth:1,borderColor:C.border},
  postedToday:{position:"absolute",top:10,right:10,backgroundColor:"rgba(3,71,80,0.4)",paddingHorizontal:10,paddingVertical:4,borderRadius:999},
  postedTodayText:{color:"#fff",fontSize:11,fontWeight:"900"},
  cardTitle:{fontSize:16,fontWeight:"800",color:C.text},
  cardMeta:{fontSize:12,color:C.subtext,marginTop:4, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap'},
  author:{color:C.text,fontWeight:"800"},
  badge:{color:C.accent,fontWeight:"800"},
  sponsoredLabel: { color: "#F7B400", fontWeight: "900", marginLeft: 4 },
  cardMsg:{fontSize:14,color:C.text,lineHeight:20,marginTop:8},
  utilityRow:{flexDirection:"row",alignItems:"center",marginTop:12,gap:8,flexWrap:"wrap"},
  utilityBtn:{flexDirection:"row",alignItems:"center",paddingHorizontal:10,paddingVertical:6,borderRadius:999,backgroundColor:C.soft,borderWidth:1,borderColor:C.border},
  utilityText:{marginLeft:6,color:C.primary,fontWeight:"800",fontSize:12},
  utilityIconBtn: { minWidth: 40, height: 40, borderRadius: 20, backgroundColor: C.soft, borderWidth: 1, borderColor: C.border, alignItems: 'center', justifyContent: 'center' },
  thumbsRow:{flexDirection:"row",gap:8,marginTop:12},
  thumb:{width:64,height:64,borderRadius:8,borderWidth:1,borderColor:C.border,backgroundColor:C.soft,overflow:"hidden"},
  thumbImg:{width:"100%",height:"100%"},
  eventRow:{marginTop:12,paddingTop:12,borderTopWidth:1,borderTopColor:C.border,flexDirection:"row",alignItems:"center",justifyContent:"space-between", flexWrap: 'wrap', gap: 8},
  eventInfo:{color:C.text,fontSize:13},
  eventBtn:{flexDirection:"row",alignItems:"center",gap:6,backgroundColor:C.primary,paddingHorizontal:12,paddingVertical:8,borderRadius:10},
  eventBtnText:{color:"#fff",fontWeight:"800",marginLeft:6,fontSize:12},
  eventCountdown: { fontSize: 13, fontWeight: "bold", color: C.primary, },
  actionsRow:{flexDirection:"row",alignItems:"center",marginTop:12,flexWrap:"wrap"},
  actionBtn:{flexDirection:"row",alignItems:"center",marginRight:16,paddingVertical:8,minHeight:44},
  actionText:{marginLeft:8,color:C.text},
  actionTextActive: { color: C.primary, fontWeight: 'bold' },
  ownerRow:{flexDirection:"row", gap:10, marginTop:12},
  alertWrap:{backgroundColor:C.soft,borderBottomWidth:1,borderBottomColor:C.border,paddingVertical:12},
  alertSlide:{width:Dimensions.get("window").width, paddingHorizontal:12},
  alertCard:{backgroundColor:C.bg, borderWidth:1, borderColor:C.border, borderRadius:14, padding:12, position: 'relative' },
  alertDismiss: { position: 'absolute', top: 4, right: 4, padding: 4, zIndex: 1 },
  alertHeader:{flexDirection:"row", alignItems:"flex-start"},
  alertIconWrap:{width:28,height:28,borderRadius:14,alignItems:"center",justifyContent:"center",backgroundColor:C.bg,marginRight:10,marginTop:2},
  alertTitle:{fontSize:15,fontWeight:"800",color:C.text, paddingRight: 18},
  alertMeta:{color:C.subtext,fontSize:12,marginTop:4},
  alertMsg:{color:C.text,fontSize:13,marginTop:8},
  alertDots:{flexDirection:"row", justifyContent:"center", marginTop:8, gap:6},
  dot:{width:6, height:6, borderRadius:3, backgroundColor:C.border},
  dotActive:{backgroundColor:C.primary},
  fab:{position:"absolute",right:18,bottom:92,width:56,height:56,borderRadius:28,backgroundColor:C.primary,alignItems:"center",justifyContent:"center",elevation:5, shadowColor:"#000", shadowOpacity:0.3, shadowRadius:4, shadowOffset:{width:0,height:2}},
  fabText:{color:"#fff",fontSize:28,fontWeight:"800"},
  bottomNav:{position:"absolute",left:0,right:0,bottom:0,backgroundColor:C.bg,flexDirection:"row",justifyContent:"space-around",alignItems:"center",paddingVertical:10,paddingBottom:34,borderTopWidth:1,borderTopColor:C.border},
  navItem:{alignItems:"center"},
  navLabel:{fontSize:12,color:C.text,marginTop:2},
  navLabelActive:{fontWeight:"900", color:C.primary},
  sectionTitle:{fontSize:18,fontWeight:"800",color:C.text},
  modalOverlay:{flex:1,backgroundColor:"rgba(0,0,0,0.35)"},
  modalFull:{flex:1,backgroundColor:C.bg,paddingTop: Platform.OS==="android"? 24 : 44, paddingHorizontal:16, borderTopLeftRadius:16, borderTopRightRadius:16},
  modalTitle:{fontSize:18,fontWeight:"900",color:C.text,marginBottom:8},
  input:{borderWidth:1,borderColor:C.border,borderRadius:10,padding:12,backgroundColor:C.bg,marginTop:8,color:C.text},
  anonRow:{flexDirection:"row",alignItems:"center",marginTop:12,justifyContent:"space-between"},
  modalActions:{flexDirection:"row",justifyContent:"flex-end",marginTop:16},
  cancel:{color:C.subtext,fontWeight:"700",marginRight:16},
  primaryBtn:{backgroundColor:C.primary,paddingHorizontal:16,paddingVertical:10,borderRadius:10},
  primaryBtnText:{color:"#fff",fontWeight:"800"},
  secondaryBtn:{borderWidth:1,borderColor:C.border,backgroundColor:C.soft,paddingHorizontal:16,paddingVertical:10,borderRadius:10},
  catRow:{flexDirection:"row",flexWrap:"wrap",marginBottom:8, marginTop: 4},
  catPill:{backgroundColor:C.soft,borderColor:C.border,borderWidth:1,paddingHorizontal:10,paddingVertical:6,borderRadius:20,marginRight:8,marginTop:8},
  catPillActive:{backgroundColor:C.primary,borderColor:C.primary},
  catPillText:{color:C.text,fontWeight:"700"},
  catPillTextActive:{color:"#fff",fontWeight:"800"},
  commentItem:{borderBottomWidth:1,borderBottomColor:C.border,paddingVertical:12},
  commentHeader:{flexDirection:"row",justifyContent:"space-between",marginBottom:4},
  commentAuthor:{fontWeight:"800",color:C.text},
  commentTime:{color:C.subtext,fontSize:12},
  commentContent:{color:C.text,fontSize:14},
  skelCard:{height:110,marginTop:12,borderRadius:14,borderWidth:1,borderColor:C.border,backgroundColor:C.soft,padding:16},
  skelLineWide:{height:16,backgroundColor:C.border,borderRadius:8,marginBottom:10},
  skelLine:{height:12,backgroundColor:C.border,borderRadius:8,marginBottom:8},
  profileHeaderRow:{flexDirection:"row",alignItems:"center",gap:12,marginTop:4},
  profileAvatar:{width:64,height:64,borderRadius:999,borderWidth:2,borderColor:C.primary,backgroundColor:C.soft, alignItems: 'center', justifyContent: 'center'},
  profileAvatarImg: { width: '100%', height: '100%', borderRadius: 999 },
  profileName:{fontSize:22,fontWeight:"900",color:C.text},
  profileTown:{color:C.subtext,marginTop:2},
  profileDivider:{height:1,backgroundColor:C.border,marginVertical:16},
  profileRow:{flexDirection:"row",alignItems:"center",paddingVertical:14,borderBottomWidth:1,borderBottomColor:C.border},
  profileRowText:{fontSize:16,fontWeight:"800",color:C.text,flex:1},
  chev:{color:C.subtext},
  helpModalSheet:{flex:1,backgroundColor:C.bg,paddingTop: Platform.OS==="android"? 24 : 36, paddingHorizontal:16, borderTopLeftRadius:16, borderTopRightRadius:16},
  toastContainer: { position: 'absolute', bottom: 100, left: 20, right: 20, backgroundColor: C.primary, padding: 12, borderRadius: 10, elevation: 6, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 4, shadowOffset: { width: 0, height: 2 } },
  toastText: { color: '#fff', fontWeight: 'bold', textAlign: 'center' },
  errorText: { color: C.error, fontSize: 12, marginTop: 4, marginLeft: 4 },
  settingsRow: { flexDirection:"row", alignItems:"center", justifyContent:"space-between", paddingVertical:12 },
  settingsLabel: { fontSize:16, color:C.text, fontWeight:"700" },
  brandFoot: { marginTop: 32, alignItems: 'center' },
  brandTag: { color: C.subtext, fontSize: 12 },
  brandVer: { color: C.border, fontSize: 10, marginTop: 4 },
  verifiedBadge: { width: 14, height: 14, marginLeft: 4 },
  headerBell: { width: 46, height: 46, alignItems: 'center', justifyContent: 'center', position: 'relative' },
  headerBellBadge: { position: 'absolute', top: 10, right: 10, backgroundColor: C.error, borderRadius: 8, minWidth: 16, height: 16, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 },
  headerBellBadgeText: { color: '#fff', fontSize: 10, fontWeight: 'bold' },
  groupItem: { flexDirection: 'row', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: C.border },
  serviceCard: { padding: 12, borderBottomWidth: 1, borderBottomColor: C.border },
  serviceHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  serviceName: { fontSize: 16, fontWeight: 'bold', color: C.text },
  serviceStatus: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, overflow: 'hidden' },
  serviceStatusText: { fontSize: 12, fontWeight: 'bold', color: '#fff' },
  serviceDetails: { color: C.subtext, marginTop: 4 },
  loginModal: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.5)' },
  loginContainer: { backgroundColor: C.bg, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 16, paddingTop: 24, maxHeight: '80%' },
  loginTitle: { fontSize: 22, fontWeight: 'bold', color: C.text, textAlign: 'center', marginBottom: 8 },
  loginSub: { color: C.subtext, textAlign: 'center', marginBottom: 16 },
  loginProfileCard: { flexDirection: 'row', alignItems: 'center', padding: 12, backgroundColor: C.soft, borderRadius: 12, marginBottom: 8, borderWidth: 1, borderColor: C.border },
  dateHeader: { paddingHorizontal: 16, paddingVertical: 8, backgroundColor: C.soft, borderBottomWidth: 1, borderBottomColor: C.border },
  dateHeaderText: { color: C.subtext, fontWeight: 'bold' },
});